const state = {
  Johor: [
    "Johor Bahru",
    "Tebrau",
    "Pasir Gudang",
    "Bukit Indah",
    "Skudai",
    "Kluang",
    "Batu Pahat",
    "Muar",
    "Ulu Tiram",
    "Senai",
    "Segamat",
    "Kulai",
    "Kota Tinggi",
    "Pontian Kechil",
    "Tangkak",
    "Yong Peng",
    "Pekan Nenas",
    "Labis",
    "Mersing",
    "Simpang Renggam",
    "Parit Raja",
    "Kelapa Sawit",
    "Buloh Kasap",
    "Chaah",
  ],
  Kedah: [
    "Sungai Petani",
    "Alor Setar",
    "Kulim",
    "Jitra",
    "Baling",
    "Pendang",
    "Yan",
    "Pokok Sena",
    "Bandar Baharu",
  ],
  Kelantan: [
    "Kota Bharu",
    "Tanah Merah",
    "Peringat",
    "Pasir Mas",
    "Gua Musang",
    "Tumpat",
  ],
  Melaka: [
    "Melaka",
    "Bukit Baru",
    "Ayer Keroh",
    "Masjid Tanah",
    "Sungai Udang",
    "Batu Berendam",
    "Alor Gajah",
    "Bukit Rambai",
    "Ayer Molek",
    "Bemban",
    "Kuala Sungai Baru",
    "Pulau Sebang",
  ],
  Negeri_Sembilan: [
    "Seremban",
    "Port Dickson",
    "Nilai",
    "Bahau",
    "Tampin",
    "Kuala Pilah",
  ],
  Pahang: [
    "Kuantan",
    "Temerloh",
    "Bentong",
    "Mentakab",
    "Raub",
    "Jerantut",
    "Pekan",
    "Kuala Lipis",
    "Bukit Tinggi",
  ],
  Perak: [
    "Ipoh",
    "Taiping",
    "Sitiawan",
    "Simpang Empat",
    "Teluk Intan",
    "Batu Gajah",
    "Lumut",
    "Kampung Koh",
    "Kuala Kangsar",
    "Tapah",
    "Bidor",
    "Parit Buntar",
    "Ayer Tawar",
    "Bagan Serai",
    "Pantai Remis",
    "Kampar",
  ],
  Perlis: ["Kangar", "Kuala Perlis"],
  Pulau_Pinang: [
    "Bukit Mertajam",
    "Georgetown",
    "Sungai Ara",
    "Gelugor",
    "Ayer Hitam",
    "Butterworth",
    "Perai",
    "Nibong Tebal",
    "Tanjung Tokong",
    "Kepala Batas",
    "Tanjung Bungah",
    "Juru",
  ],
  Sabah: [
    "Kota Kinabalu",
    "Sandakan",
    "Tawau",
    "Lahad Datu",
    "Keningau",
    "Putatan",
    "Donggongon",
    "Semporna",
    "Kudat",
    "Kunak",
    "Papar",
    "Ranau",
    "Beaufort",
    "Kinarut",
    "Kota Belud",
  ],
  Sarawak: [
    "Kuching",
    "Miri",
    "Sibu",
    "Bintulu",
    "Limbang",
    "Sarikei",
    "Sri Aman",
    "Kapit",
    "Kota Samarahan",
  ],
  Selangor: [
    "Subang Jaya",
    "Klang",
    "Shah Alam",
    "Petaling Jaya",
    "Cheras",
    "Kajang",
    "Selayang",
    "Rawang",
    "Semenyih",
    "Banting",
    "Balakong",
    "Gombak",
    "Kuala Selangor",
    "Serendah",
    "Bukit Beruntung",
    "Jenjarom",
    "Sungai Besar",
    "Batu Arang",
    "Tanjung Sepat",
    "Kuang",
    "Batang Berjuntai",
    "Bandar Baru Salak Tinggi",
    "Sekinchan",
    "Sabak",
    "Tanjung Karang",
    "Beranang",
    "Sungai Pelek",
  ],
  Terengganu: [
    "Kuala Terengganu",
    "Chukai",
    "Dungun",
    "Kuala Berang",
    "Marang",
    "Paka",
    "Jerteh",
  ],
  Wilayah_Persekutuan: ["Kuala Lumpur", "Labuan", "Putrajaya"],
};

export default state;
